  ---
title: "connect"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls(all=TRUE))
```



```{r}
setwd("C:/Users/prithvi/Desktop/connect")
connect_data=read.csv("connect-4.csv")
```

```{r}
str(connect_data)
```

```{r}
summary(connect_data)
```

```{r}
sum(is.na(connect_data))

```

```{r}
dim(connect_data)
```



```{r}
head(connect_data)
tail(connect_data)
```




```{r}
result=connect_data$win
connect_data1=cbind(connect_data,result)
connect_data1$win=NULL

```



```{r}
library(dummies)
connect_data2=dummy.data.frame(connect_data1[,-43])
str(connect_data2)
```
```{r}
connect_data3=cbind(connect_data2,result)
```
```{r}
pca_data <- prcomp(connect_data3[,-127], scale = F)
summary(pca_data)
```
```{r}
connect_data3_pca <- as.data.frame(predict(pca_data, connect_data3))[1:55]
result_pca=connect_data3$result
connect_data3_pca=cbind(connect_data3_pca,result_pca)

```

```{r}
library(caret)
set.seed(123)
train_rows <- createDataPartition(connect_data3_pca$result_pca, p = 0.7, list = F)

train_data <- connect_data3_pca[train_rows,]

test_data <-connect_data3_pca[-train_rows,]
str(train_data)

write.csv(train_data,file = "train_data_pca.csv")
write.csv(test_data,file="test_data_pca.csv")

write.csv(train_data,file = "train_data.csv")
write.csv(test_data,file="test_data.csv")
```

```{r}
table(train_data$result_pca)

train1<-train_data[train_data$result=='win'|train_data$result=='draw',]

```

```{r}
table(train1$result_pca)
train1$result_pca<-factor(train1$result_pca)
```
```{r}
library(DMwR)
attach(train1)
smote_data1=SMOTE(result_pca  ~.,train1,perc.over =400 ,k=5,perc.under = 100,learner = NULL)
table(smote_data1$result_pca)
```
```{r}
train2<-train_data[train_data$result_pca=='win'|train_data$result_pca=='loss',]
train2$result_pca<-factor(train2$result_pca)
table(train2$result_pca)
```

```{r}
library(DMwR)
attach(train2)
smote_data2=SMOTE(result_pca  ~.,train2,perc.over =150 ,k=5,perc.under = 100,learner = NULL)
table(smote_data2$result_pca)

```


```{r}

smote_data<-rbind(smote_data1,smote_data2[smote_data2$result_pca=='loss',])
write.csv(smote_data,file="smote_data.csv")

 ```


```{r}
#library(DMwR)
#attach(train_data)
#smote_data=SMOTE(result_pca  ~.,train_data,perc.over =400 ,k=5,perc.under = 100,learner = NULL)
table(smote_data$result_pca)
```

```{r}
summary(smote_data)
setwd("C:/Users/prithvi/Desktop/connect")
test_data=read.csv("file:///C:/Users/prithvi/Desktop/connect/test_data_pca.csv")
smote_data=read.csv("file:///C:/Users/prithvi/Desktop/connect/smote_data.csv",header = T)
```

##DECISION TREE C5
```{r}
library(C50)
C5_tree=C5.0(result_pca ~ .,smote_data)
smote_data=read.csv("file:///C:/Users/prithvi/Desktop/connect/smote_data1.csv")
test_data=read.csv("file:///C:/Users/prithvi/Desktop/connect/test_data.csv")
```

```{r}
C5_rules=C5.0(result_pca ~ .,smote_data,rules=T)

```

```{r}
C5imp(C5_tree,metric = "usage")
```

```{r}

```

```{r}
library(C50)
fit <- C5.0(result_pca ~ ., data = smote_data,method="class")

```

```{r}
preds=predict(C5_tree,test_data)

```

```{r}
library(caret)
library(e1071)
confusionMatrix(preds,test_data$result_pca)
preds1=predict(C5_tree,smote_data)
confusionMatrix(preds1,smote_data$result_pca)

trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
c5_fit <- train(result_pca~., data = smote_data, method = "C5.0", trControl=trctrl,preProcess = c("center","scale"),tuneLength = 10)

preds_c5_pt=predict(c5_fit,test_data)
confusionMatrix(preds_c5_pt,test_data$result_pca)

preds_c5_train_pt=predict(c5_fit,smote_data)
confusionMatrix(preds_c5_train_pt,smote_data$result_pca)
```


##RANDOM FOREST
```{r}
library(caret)
library(randomForest)
model_rf = randomForest(result_pca ~ . ,smote_data,ntress=1500)
importance(model_rf)
varImpPlot(model_rf)
preds_rf =predict(model_rf,test_data)


confusionMatrix(preds_rf, test_data$result_pca)
preds_train_rf= predict(model_rf,smote_data)
confusionMatrix(preds_train_rf,smote_data$result_pca)

ctrl <- trainControl(method="repeatedcv",repeats = 3)
#rf.grid <- expand.grid(.mtry=7:20)
#model_rfval<-train(X1~.,data=train_datanew1,method='rf',trControl=ctrl,tuneLength=3,tuneGrid=rf.grid)
rf.grid <- expand.grid(.mtry=7)
model_rfval<-train(result_pca~.,data=smote_data,method='rf',trControl=ctrl,tuneLength=3,tuneGrid=rf.grid)

preds_rf_pt =predict(model_rfval,test_data)

confusionMatrix(preds_rf_pt, test_data$result_pca)
preds_train_rfpt= predict(model_rfval,smote_data)
confusionMatrix(preds_train_rfpt,smote_data$result_pca)



control1 <- trainControl(method="repeatedcv", number=10, repeats=3, search="random")
set.seed(123)
mtry1 <- sqrt(ncol(56))
rf_random <- train(result_pca ~ ., data=smote_data, method="rf",  tuneLength=15, trControl=control1)
print(rf_random)
plot(rf_random)

```
##Linear SVM
```{r}
 
library(e1071)

model_svm <- svm(result_pca ~ . , smote_data, kernel = "linear")

summary(model_svm)
preds_svm <- predict(model_svm, test_data)

confusionMatrix(preds_svm, test_data$result_pca)
preds_train_svm <- predict(model_svm,smote_data)
confusionMatrix(preds_train_svm,smote_data$result_pca)




```
## Tanhdot kernel SVM
```{r}
library(kernlab)
model_svm_th <- ksvm(result_pca ~ . , smote_data, kernel = "tanhdot")
preds_svm_th <- predict(model_svm_th, test_data)

confusionMatrix(preds_svm_th, test_data$result_pca)
preds_train_svm_th <- predict(model_svm_th,smote_data)
confusionMatrix(preds_train_svm_th,smote_data$result_pca)

```
##SVM ANOVA
```{r}
model_svm_an <- ksvm(result_pca ~ . , train_data, kernel = "anovadot")
##  Setting default kernel parameters
preds_svm_an <- predict(model_svm_an, test_data)

confusionMatrix(preds_svm_an, test_data$result_pca)
preds_train_svm_an <- predict(model_svm_th,smote_data)
confusionMatrix(preds_train_svm_an, smote_data$result_pca)

```
##tahndot
```{r}
model_svm_th=ksvm(result ~.,smote_data,kernel="tanhdot")
summary(model_svm_th)
preds_svm_th=predict(model_svm_th,test_data)
confusionMatrix(preds_svm_th,test_data$result)
preds_train_svm_th=predict(model_svm_th,smote_data)
confusionMatrix(preds_train_svm_th,smote_data$result)
```



## Decision Trees CART
```{r}

library(rpart)
library(caret)

model_dt <- rpart(result_pca ~ . , smote_data)
preds_dt <- predict(model_dt, test_data)

preds_tree <- ifelse(preds_dt[, 1] > preds_dt[, 2]&preds_dt[,1]>preds_dt[,3],"win" , ifelse(preds_dt[,2]>preds_dt[,1]&preds_dt[,2]>preds_dt[,3] ,"draw" , "loss"))

confusionMatrix(preds_tree, test_data$result_pca)
preds_train_dt <- predict(model_dt,smote_data)

preds_train_tree <- ifelse(preds_train_dt[, 1] > preds_train_dt[, 2]&preds_train_dt[,1]>preds_train_dt[,3],"win" , ifelse(preds_train_dt[,2]>preds_train_dt[,1]&preds_train_dt[,2]>preds_train_dt[,3] ,"draw" , "loss"))
str(smote_data)
confusionMatrix (preds_train_tree,smote_data$result_pca)
result_pca_1<-subset(smote_data,select=-c(result_pca))

ctrl <- trainControl(method="repeatedcv",repeats = 3)
rpart.grid <- expand.grid(.cp=seq(0.01,.2,.01))
model_rpart<-caret::train(y=smote_data$result_pca,x=result_pca_1,method="rpart")
getModelInfo("rpart")
modelLookup("rpart")
dim(smote_data)
length(smote_data$result_pca)
preds_dt_testpt <- predict(model_rpart, test_data)
confusionMatrix(preds_dt_testpt,test_data$result_pca)

preds_dt_trainpt <- predict(model_rpart, smote_data)
confusionMatrix(preds_dt_trainpt,smote_data$result_pca)
```


```{r}


```
##knn
```{r}
library(caret)
model_knn <- knn3(result_pca ~ . , smote_data, k = 8)


ctrl <- trainControl(method="repeatedcv",repeats = 3)
rpart.grid <- expand.grid(.cp=seq(0.01,.2,.01))
model_rpart<-caret::train(y=smote_data$result_pca,x=result_pca_1,method="knn")

preds_k <- predict(model_knn, test_data)
preds_knn <- ifelse(preds_k[, 1] > preds_k[, 2]&preds_k[,1]>preds_k[,3],"win" , ifelse(preds_k[,2]>preds_k[,1]&preds_k[,2]>preds_k[,3] ,"draw" , "loss"))

confusionMatrix(preds_knn, test_data$result)
preds_train_k <- predict(model_knn, smote_data)

preds_train_knn <- ifelse(preds_train_k[, 1] > preds_train_k[, 2]&preds_train_k[,1]>preds_train_k[,3],"win" , ifelse(preds_train_k[,2]>preds_train_k[,1]&preds_train_k[,2]>preds_train_k[,3] ,"draw" , "loss"))

confusionMatrix(preds_train_knn,smote_data$result)

```
## Bagged Decision Trees

```{r}
library(rpart)
library(ipred)
set.seed(1234)

model_tree_bag <- bagging(result ~ . , data=smote_data, control = rpart.control(cp = 0.01, xval = 10))
preds_tree_bag <- predict(model_tree_bag, test_data)

confusionMatrix(preds_tree_bag, test_data$result)
preds_train_tree_bag <- predict(model_tree_bag,smote_data)
confusionMatrix(preds_train_tree_bag,smote_data$result)
```
## navie bayes

```{r}
library(e1071)
model_nb<-naiveBayes(result~.,smote_data)
preds_nb <- predict(model_nb, test_data)
preds_train_nb<-predict(model_nb,smote_data)

confusionMatrix(preds_nb, test_data$result)

confusionMatrix(preds_train_nb, smote_data$result)


```


#Neural network
```{r}
library(neuralnet)
library(mxnet)
library(caret)
set.seed(1234)
intrain = createDataPartition(y = smote_data$result, p=0.7, list = F)
train.x = data.matrix(smote_data[intrain, -56])
train.y = smote_data[intrain, 56]
test.x = data.matrix(smote_data[-intrain, -56])
test.y = smote_data[-intrain, 56]

mx.set.seed(0)
Sys.time() -> start
model <- mx.mlp(train.x, train.y, hidden_node=c(10), out_node=2, activation="tanh", out_activation="softmax",
                 num.round=20, array.batch.size=100, learning.rate=0.07, momentum=0.9,
                 eval.metric=mx.metric.accuracy)
 Sys.time() -> end
 paste(end - start)
 
preds = predict(model, test.x)

preds=t(preds)
pred.label = ifelse(preds[,2]<0.55, 0, 1)

conf.mat = table(pred.label, test.y);conf.mat
accuracy = sum(diag(conf.mat))/sum(conf.mat);accuracy
precision = conf.mat[2,2]/sum(conf.mat[2,]);precision
recall = conf.mat[2,2]/sum(conf.mat[,2]);recall

table(test.y)




```

```{r}
smote_data$result_pca <- as.numeric(smote_data$result_pca)

test_data$result_pca <- as.numeric(test_data$result_pca)


library(gbm)
model_gbm <- gbm(result_pca ~ . , cv.folds = 8, interaction.depth = 3, 
                 shrinkage = 0.005, distribution= 'bernoulli',
                 data = smote_data, n.trees = 1600)


gbm.perf(model_gbm)


preds_g <- predict(model_gbm, type = 'response')
install.packages("pROC")
library(pROC)

# Let's create an roc object using the roc function
gbm_roc <- roc(smote_data$result_pca, preds_g)


# Get to the cutoff value using the coords() function

cutoff_gbm <- coords(gbm_roc, "best", ret = "threshold")


preds_train_gbm <- ifelse(preds_g >= cutoff_gbm, 1, 0)

preds_test_g <- predict(model_gbm, test_data, type = 'response')

preds_gbm <- ifelse(preds_test_g >= cutoff_gbm, 1, 0)

confusionMatrix(preds_gbm, test_data$result_pca)

```
##BAGGING
```{r}
library(rpart)
library(ipred)

set.seed(1234)

model_bag <- bagging(result ~ . , data=smote_data, control = rpart.control(cp = 0.01, xval = 10))
preds_bag <- predict(model_tree_bag, test_data)

confusionMatrix(preds_bag, test_data$result)
preds_train_bag <- predict(model_bag,smote_data)
confusionMatrix(preds_train_bag,smote_data$result)

```
##Stacking
```{r}
library(class)
train_preds_df <- data.frame( rf = preds_train_rf,svm=preds_train_svm,svmth=preds_train_svm_th, 
                       tree = preds_train_tree, tree_bag = preds_train_tree_bag,nb=preds_train_nb,
                       result = newdata$result)

test_preds_df <- data.frame( rf = preds_rf,c5=preds,svm=preds_svm,svmth=preds_svm_th,
                       tree = preds_tree, tree_bag = preds_tree_bag,nb=preds_nb, 
                       result= test_data$result)

stack_df <- rbind(train_preds_df, test_preds_df)

stack_df$result_pca <- as.factor(stack_df$result_pca)

numeric_st_df <- sapply(stack_df[, !(names(stack_df) %in% "result")], 
                        function(x) as.numeric(as.character(x)))

pca_stack <- prcomp(numeric_st_df, scale = F)
predicted_stack <- as.data.frame(predict(stack_df, numeric_st_df))

stacked_df <- data.frame(predicted_stack, Cancer = stack_df[, (names(stack_df) %in% "Cancer")])
```
##logistic
```{r}


```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

