---
title: "models"
author: "prudhvi"
date: "31 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/prithvi/Desktop/connect")
smote_data=read.csv("file:///C:/Users/prithvi/Desktop/connect/smote_data1.csv")
test_data=read.csv("file:///C:/Users/prithvi/Desktop/connect/test_data.csv")
```
##c5
```{r}
library(C50)
C5_tree=C5.0(result ~ .,smote_data)
C5_rules=C5.0(result ~ .,smote_data,rules=T)
preds=predict(C5_tree,test_data)
library(caret)
library(e1071)
confusionMatrix(preds,test_data$result)
preds1=predict(C5_tree,smote_data)
confusionMatrix(preds1,smote_data$result)
```
##random forest
```{r}
library(caret)
library(randomForest)
model_rf = randomForest(result ~ . ,smote_data,ntress=1500)
importance(model_rf)
varImpPlot(model_rf)
preds_rf =predict(model_rf,test_data)


confusionMatrix(preds_rf, test_data$result)
preds_train_rf= predict(model_rf,smote_data)
confusionMatrix(preds_train_rf,smote_data$result)
```
##linear svm
```{r}
library(e1071)

model_svm <- svm(result ~ . , smote_data, kernel = "linear")

summary(model_svm)
preds_svm <- predict(model_svm, test_data)

confusionMatrix(preds_svm, test_data$result)
preds_train_svm <- predict(model_svm,smote_data)
confusionMatrix(preds_train_svm,smote_data$result)
```
##thandot
```{r}
library(kernlab)
model_svm_th <- ksvm(result ~ . , smote_data, kernel = "tanhdot")
preds_svm_th <- predict(model_svm_th, test_data)

confusionMatrix(preds_svm_th, test_data$result)
preds_train_svm_th <- predict(model_svm_th,smote_data)
confusionMatrix(preds_train_svm_th,smote_data$result)
```
##anova
```{r}
model_svm_an <- ksvm(result ~ . , train_data, kernel = "anovadot")
##  Setting default kernel parameters
preds_svm_an <- predict(model_svm_an, test_data)

confusionMatrix(preds_svm_an, test_data$result)
preds_train_svm_an <- predict(model_svm_th,smote_data)
confusionMatrix(preds_train_svm_an, smote_data$result)
```
##cart
```{r}
library(rpart)
library(caret)

model_dt <- rpart(result ~ . , smote_data)
preds_dt <- predict(model_dt, test_data)

preds_tree <- ifelse(preds_dt[, 1] > preds_dt[, 2]&preds_dt[,1]>preds_dt[,3],"win" , ifelse(preds_dt[,2]>preds_dt[,1]&preds_dt[,2]>preds_dt[,3] ,"draw" , "loss"))

confusionMatrix(preds_tree, test_data$result)
preds_train_dt <- predict(model_dt,smote_data)

preds_train_tree <- ifelse(preds_train_dt[, 1] > preds_train_dt[, 2]&preds_train_dt[,1]>preds_train_dt[,3],"win" , ifelse(preds_train_dt[,2]>preds_train_dt[,1]&preds_train_dt[,2]>preds_train_dt[,3] ,"draw" , "loss"))
str(smote_data)
confusionMatrix (preds_train_tree,smote_data$result)


```
##knn
```{r}
library(caret)
model_knn <- knn3(result_pca ~ . , smote_data, k = 12)


ctrl <- trainControl(method="repeatedcv",repeats = 3)
rpart.grid <- expand.grid(.cp=seq(0.01,.2,.01))
model_rpart<-caret::train(y=smote_data$result_pca,x=result_pca_1,method="knn")

preds_k <- predict(model_knn, test_data)
preds_knn <- ifelse(preds_k[, 1] > preds_k[, 2]&preds_k[,1]>preds_k[,3],"win" , ifelse(preds_k[,2]>preds_k[,1]&preds_k[,2]>preds_k[,3] ,"draw" , "loss"))

confusionMatrix(preds_knn, test_data$result)
preds_train_k <- predict(model_knn, smote_data)

preds_train_knn <- ifelse(preds_train_k[, 1] > preds_train_k[, 2]&preds_train_k[,1]>preds_train_k[,3],"win" , ifelse(preds_train_k[,2]>preds_train_k[,1]&preds_train_k[,2]>preds_train_k[,3] ,"draw" , "loss"))

confusionMatrix(preds_train_knn,smote_data$result)
```
##bagged decision decission
```{r}
library(rpart)
library(ipred)
set.seed(1234)

model_tree_bag <- bagging(result ~ . , data=smote_data, control = rpart.control(cp = 0.01, xval = 10))
preds_tree_bag <- predict(model_tree_bag, test_data)

confusionMatrix(preds_tree_bag, test_data$result)
preds_train_tree_bag <- predict(model_tree_bag,smote_data)
confusionMatrix(preds_train_tree_bag,smote_data$result)
```
##navie bayes
```{r}
library(e1071)
model_nb<-naiveBayes(result~.,smote_data)
preds_nb <- predict(model_nb, test_data)
preds_train_nb<-predict(model_nb,smote_data)

confusionMatrix(preds_nb, test_data$result)

confusionMatrix(preds_train_nb, smote_data$result)

```
##bagging
```{r}
library(rpart)
library(ipred)

set.seed(1234)

model_bag <- bagging(result ~ . , data=smote_data, control = rpart.control(cp = 0.01, xval = 10))
preds_bag <- predict(model_tree_bag, test_data)

confusionMatrix(preds_bag, test_data$result)
preds_train_bag <- predict(model_bag,smote_data)
confusionMatrix(preds_train_bag,smote_data$result)
```
##logistic
```{r}
library(glmnet)
library(Matrix)

reg <- model.matrix(result~., data = smote_data)
reg1 <- model.matrix(test_data$result~., data = test_data)

 lm = cv.glmnet(reg,smote_data$result,family = "multinomial",alpha =1)
 lm$lambda.min
 
 
log_reg<-glmnet(reg,smote_data$result,family = "multinomial",alpha =0,lambda =lm$lambda.min)
preds_test_lr <- predict(log_reg, reg1,type = "class")
preds_train_lr<-predict(log_reg, reg,type = "class")

confusionMatrix(preds_test_lr, test_data$result)

confusionMatrix(preds_train_lr, smote_data$result)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

