 ---
title: "connect"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls(all=TRUE))
```



```{r}
setwd("C:/Users/prithvi/Desktop/connect")
connect_data=read.csv("connect-4.csv")
```

```{r}
str(connect_data)
```

```{r}
summary(connect_data)
```

```{r}
sum(is.na(connect_data))

```

```{r}
dim(connect_data)
```



```{r}
head(connect_data)
tail(connect_data)
```




```{r}
result=connect_data$win
connect_data1=cbind(connect_data,result)
connect_data1$win=NULL

```

```{r}
library(dummies)
connect_data2=dummy.data.frame(connect_data1[,-43])
str(connect_data2)
```
```{r}
connect_data3=cbind(connect_data2,result)
```
```{r}
pca_data <- prcomp(connect_data3[,-127], scale = F)
summary(pca_data)
```
```{r}
connect_data3_pca <- as.data.frame(predict(pca_data, connect_data3))[1:45]
result_pca=connect_data3$result
connect_data3_pca=cbind(connect_data3_pca,result_pca)

```

```{r}
library(caret)
set.seed(123)
train_rows <- createDataPartition(connect_data3_pca$result_pca, p = 0.7, list = F)

train_data <- connect_data3_pca[train_rows,]

test_data <-connect_data3_pca[-train_rows,]
str(train_data)

 
```



```{r}
library(C50)
C5_tree=C5.0(result_pca ~ .,train_data)

```

```{r}
C5_rules=C5.0(result_pca ~ .,train_data,rules=T)

```

```{r}
C5imp(C5_tree,metric = "usage")
```

```{r}
summary(C5_rules)
```

```{r}

```

```{r}
preds=predict(C5_tree,test_data)
```

```{r}
library(caret)
library(e1071)
confusionMatrix(preds,test_data$result_pca)

```


```{r}

library(randomForest)
model_rf = randomForest(result_pca ~ . ,train_data)
importance(model_rf)
varImpPlot(model_rf)
preds_rf =predict(model_rf,test_data)

confusionMatrix(preds_rf, test_data$result_pca)
preds_train_rf= predict(model_rf)


```
##Linear SVM
```{r}
 
library(e1071)

model_svm <- svm(result_pca ~ . , train_data, kernel = "linear")

summary(model_svm)
preds_svm <- predict(model_svm, test_data)

confusionMatrix(preds_svm, test_data$result_pca)
preds_train_svm <- predict(model_svm)




```
## Tanhdot kernel SVM
```{r}
library(kernlab)
model_svm_th <- ksvm(result_pca ~ . , train_data, kernel = "tanhdot")
preds_svm_th <- predict(model_svm_th, test_data)

confusionMatrix(preds_svm_th, test_data$result_pca)
preds_train_svm_th <- predict(model_svm_th)

```





## Decision Trees
```{r}

library(rpart)

model_dt <- rpart(result_pca ~ . , train_data)
preds_dt <- predict(model_dt, test_data)

preds_tree <- ifelse(preds_dt[, 1] > preds_dt[, 2]&preds_dt[,1]>preds_dt[,3],"win" , ifelse(preds_dt[,2]>preds_dt[,1]&preds_dt[,2]>preds_dt[,3] ,"draw" , "loss"))

confusionMatrix(preds_tree, test_data$result_pca)


```


```{r}
svm_test <- predict(model_svm, test_data)
confusionMatrix(svm_test, test_data$win)


```
##knn
```{r}
model_knn <- knn3(result_pca ~ . , train_data, k = 5)

preds_k <- predict(model_knn, test_data)
preds_knn <- ifelse(preds_dt[, 1] > preds_dt[, 2]&preds_dt[,1]>preds_dt[,3],"win" , ifelse(preds_dt[,2]>preds_dt[,1]&preds_dt[,2]>preds_dt[,3] ,"draw" , "loss"))

confusionMatrix(preds_knn, test_data$result_pca)
preds_train_k <- predict(model_knn, train_data)

preds_train_knn <- ifelse(preds_dt[, 1] > preds_dt[, 2]&preds_dt[,1]>preds_dt[,3],"win" , ifelse(preds_dt[,2]>preds_dt[,1]&preds_dt[,2]>preds_dt[,3] ,"draw" , "loss"))

knn_test <- ifelse(predict(model_knn, test_data)[, 1] > preds_dt[, 2]&preds_dt[,1]>preds_dt[,3],"win" , ifelse(preds_dt[,2]>preds_dt[,1]&preds_dt[,2]>preds_dt[,3] ,"draw" , "loss"))


```
## Bagged Decision Trees

```{r}
library(ipred)
set.seed(1234)

model_tree_bag <- bagging(result_pca ~ . , data=train_data, control = rpart.control(cp = 0.01, xval = 10))
preds_tree_bag <- predict(model_tree_bag, test_data)

confusionMatrix(preds_tree_bag, test_data$result_pca)
preds_train_tree_bag <- predict(model_tree_bag)

```
## STACKING Model

```{r}
# Getting all the predictions on the train data into a dataframe

train_preds_df <- data.frame(svm = preds_train_svm, svm_th = preds_train_Tan,
                       rf = preds_train_RF, knn = preds_train_knn,
                       tree = preds_train_tree, tree_bag = preds_train_tree_bag,
                       gbm = preds_train_gbm,result= train_data$result_pca)
```

```

```

```

```
```{r}


```

```{r}

```

